global:
  scrape_interval: 10s
scrape_configs:
  - job_name: qs
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true 
    static_configs:
      - targets: ['host.docker.internal:7239'] 